### ISSUE TITLE
Write Hackathon challenge statement

### ISSUE THREAD

**Issue by kaylarobinson077** [Code-For-Chicago/Code-for-Chicago-Data-Workgroup#18]

**Comment by caramkarter** [comment]
Possible next steps:
1) Look at other fields not included in current analysis: a) look at relationship by organization ID - are some rescue organizations moving dogs faster? b) look at variables related to the actual listing content - number of photos included on listing; length of description provided; etc. - to share possible best practices for listing these dogs on Petfinder
2) Expand dataset to other major metro areas in the US to look at differences
